stages:
  - check
  - php
  - build
  - behave-test
  - release

variables:
  DOCKER_HOST: tcp://docker:2375
  GIT_DEPTH: 10
  GIT_SUBMODULE_STRATEGY: recursive

unit-test-lint:
  stage: check
  image: cimg/go:1.20
  before_script:
    - git config --global url."ssh://git@github.com/".insteadOf "https://github.com/"
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo 'github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl' >> ~/.ssh/known_hosts
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
    - echo "$SSH_PUBLIC_KEY" > ~/.ssh/id_ed25519.pub
    - chmod 400 ~/.ssh/id_*
  script:
    # Fake some files to avoid the compiler or "typecheck" linter complaining about a missing embedded file.
    - touch internal/legacy/archives/php_linux_amd64 internal/legacy/archives/platform.phar
    - make lint test
  coverage: '/total:\s+\(statements\)\s+\d+.\d+%/'

build-php-linux-x86:
  stage: php
  image: docker:20.10-git
  services:
    - docker:20.10-dind
  before_script:
    - apk add -U make
    - mkdir -p internal/legacy/archives
  script:
    - make php
  artifacts:
    paths:
      - internal/legacy/archives/*
    expire_in: 1 day

build-php-linux-arm:
  stage: php
  image: docker:20.10-git
  services:
    - docker:20.10-dind
  before_script:
    - apk add -U make
    - mkdir -p internal/legacy/archives
  script:
    - make php
  artifacts:
    paths:
      - internal/legacy/archives/*
    expire_in: 1 day
  tags:
    - arm-high-cpu

build-php-windows:
  stage: php
  image: docker:20.10-git
  before_script:
    - apk add -U make wget
    - mkdir -p internal/legacy/archives
  script:
    - make php GOOS=windows GOARCH=amd64
  artifacts:
    paths:
      - internal/legacy/archives/*
    expire_in: 1 day

build-php-macos-arm:
  stage: php
  before_script:
    - export PATH="/opt/homebrew/bin:$PATH"
  script:
    - make php
  artifacts:
    paths:
      - internal/legacy/archives/*
    expire_in: 1 day
  tags:
    - macos-arm

build-php-macos-x86:
  stage: php
  script:
    - make php
  artifacts:
    paths:
      - internal/legacy/archives/*
    expire_in: 1 day
  tags:
    - macos-x86

build:
  stage: build
  before_script:
    - export PATH="/opt/homebrew/bin:$PATH"
    - brew install gon goreleaser wget
  script:
    - make snapshot
  dependencies:
    - build-php-linux-arm
    - build-php-linux-x86
    - build-php-macos-arm
    - build-php-macos-x86
    - build-php-windows
  artifacts:
    paths:
      - dist/
    expire_in: 1 day
  tags:
    - macos-arm

behave-test-linux:
  stage: behave-test
  dependencies:
    - build
  variables:
    PATH_CLI: platform_linux_amd64_v1/platform
  before_script:
    - apt-get install -y python3 python3-pip
    - pip3 install --no-cache-dir behave sh selenium requests
  script:
    - bash tests/test-behave.sh
  image: pjcdawkins/platformsh-cli

release:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - export PATH="/opt/homebrew/bin:$PATH"
    - brew install gon goreleaser wget
    - git remote set-url origin https://github.com/platformsh/cli
  script:
    - make release
  dependencies:
    - unit-test-lint
    - behave-test-linux
    - build-php-linux-arm
    - build-php-linux-x86
    - build-php-macos-arm
    - build-php-macos-x86
    - build-php-windows
  tags:
    - macos-arm
