stages:
  - php
  - build
  - test
  - release

variables:
  DOCKER_HOST: tcp://docker:2375
  GIT_DEPTH: 10
  GIT_SUBMODULE_STRATEGY: recursive

build-php-linux-x86:
  stage: php
  image: docker:20.10-git
  services:
    - docker:20.10-dind
  before_script:
    - apk add -U make
    - mkdir -p legacy/archives
  script:
    - make php
  artifacts:
    paths:
      - legacy/archives/*
    expire_in: 1 day

build-php-linux-arm:
  stage: php
  image: docker:20.10-git
  services:
    - docker:20.10-dind
  before_script:
    - apk add -U make
    - mkdir -p legacy/archives
  script:
    - make php
  artifacts:
    paths:
      - legacy/archives/*
    expire_in: 1 day
  tags:
    - arm-high-cpu

build-php-windows:
  stage: php
  image: docker:20.10-git
  before_script:
    - apk add -U make wget
    - mkdir -p legacy/archives
  script:
    - make php GOOS=windows GOARCH=amd64
  artifacts:
    paths:
      - legacy/archives/*
    expire_in: 1 day

build-php-macos-arm:
  stage: php
  before_script:
    - export PATH="/opt/homebrew/bin:$PATH"
  script:
    - make php
  artifacts:
    paths:
      - legacy/archives/*
    expire_in: 1 day
  tags:
    - macos-arm

build-php-macos-x86:
  stage: php
  script:
    - make php
  artifacts:
    paths:
      - legacy/archives/*
    expire_in: 1 day
  tags:
    - macos-x86

build:
  stage: build
  before_script:
    - export PATH="/opt/homebrew/bin:$PATH"
    - brew install gon goreleaser wget
  script:
    - make snapshot
  dependencies:
    - build-php-linux-arm
    - build-php-linux-x86
    - build-php-macos-arm
    - build-php-macos-x86
    - build-php-windows
  artifacts:
    paths:
      - dist/
    expire_in: 1 day
  tags:
    - macos-arm

test-linux:
  stage: test
  dependencies:
    - build
  variables:
    PATH_CLI: platform_linux_amd64_v1/platform
  before_script:
    - apt-get install -y python3 python3-pip
    - pip3 install --no-cache-dir behave sh selenium requests
  script:
    - bash tests/test-behave.sh
  image: pjcdawkins/platformsh-cli

release:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - export PATH="/opt/homebrew/bin:$PATH"
    - brew install gon goreleaser wget
    - git remote set-url origin https://github.com/platformsh/cli
  script:
    - make release
  dependencies:
    - test-linux
    - build-php-linux-arm
    - build-php-linux-x86
    - build-php-macos-arm
    - build-php-macos-x86
    - build-php-windows
  tags:
    - macos-arm
